name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for better context

      - name: Claude Code Review
        uses: anthropics/claude-code-action@v1
        with:
          # Store your Anthropic API key as a secret in your repository settings
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # Use a cost-effective model for automated reviews
          model: 'claude-3-5-sonnet-20240620'
          prompt: |
            You are a senior software architect reviewing a pull request.
            Your goal is to provide a high-level review focusing on logic, potential bugs, and adherence to the project's best practices as outlined in CLAUDE.md.
            Do NOT comment on minor style issues, as a linter will handle those.
            Provide your feedback as a concise list of suggestions. If there are no major issues, simply approve the PR with a positive comment.
